FROM kolla/centos-binary-ironic-base:1.1.3
MAINTAINER Kolla Project (https://launchpad.net/kolla)


    

RUN yum -y install \
    openstack-ironic-inspector \
    && yum clean all

    




USER ironic