FROM kolla/centos-binary-murano-base:1.1.3
MAINTAINER Kolla Project (https://launchpad.net/kolla)


    


COPY extend_start.sh /usr/local/bin/kolla_murano_extend_start
RUN chmod 755 /usr/local/bin/kolla_murano_extend_start



USER murano