FROM kolla/centos-binary-ceilometer-base:1.1.3
MAINTAINER Kolla Project (https://launchpad.net/kolla)


    

RUN yum install -y openstack-ceilometer-notification \
  && yum clean all

    




USER ceilometer