FROM kolla/centos-binary-cinder-base:1.1.3
MAINTAINER Kolla Project (https://launchpad.net/kolla)


    

RUN yum install -y \
        lvm2 \
        scsi-target-utils \
    && yum clean all

   




USER cinder